### PR TITLE
Check for root directory rename in setup script.

### PR DESCRIPTION
**Pull request by winder**
The project name is generic, so I renamed my local directory `ziggurat-algorand`. This updates the setup script to support a renamed project directory.

### CODE REVIEW

**Review by Rqnsom — APPROVED** [review]
Great, thanks!
LGTM 👍

**Comment by niklaslong** [comment]
Hi @winder, thank you for the contribution. One last thing, would you mind updating the commit message to follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)? We use this project-wide. Thanks!

**Comment by winder** [comment]
I amended the commit message, let me know if this isn't what you had in mind

**Comment by niklaslong** [comment]
Perfect, thanks @winder!

**Pull request merged**
