### PR TITLE
chore: update description for ignored tests

### PR DESCRIPTION
**Pull request by Rqnsom**
The only actual diff in [tests/performance/get_blocks.rs](https://github.com/runziggurat/algorand/pull/70/files#diff-78b65b6769d31e70406b04b3d4d9def2f35c4792a8aff98201c1bab7c707e9c1) is:

```
#[cfg_attr(
    not(feature = "performance"),
    ignore = "run this test with the 'performance' feature enabled"
)]
```

Why is git doing this... 🤔

### CODE REVIEW

**Review by asmie — COMMENTED** [review]
Just some idea - maybe all the internal tests should be a feature that can be enabled and disabled just like the performance tests.
Maybe we should prefix them with:
```
#[cfg_attr(
    not(feature = "internal"),
    ignore = "run this test with the 'internal' feature enabled"
)]
```

It would allow anyone to easily enable different subset of tests, even the internal ones that check correctness of implementation.

**Comment by Rqnsom** [comment]
haha yeah, cool idea, but not everything needs to be a feature - one can run all featureless and ignored (which are all sort of 'internal' by default) tests with
`cargo test -- --ignored`

sometimes we will want to explain why the certain internal test is ignored, which won't be possible with "run this test with the 'internal' feature enabled" text taking that place (which is shown when we run `cargo test`)

e.g. description below is pretty concise and simple (and to run it one would need to use `--ignored` option anyway):
```
#[allow(non_snake_case)]
#[ignore = "a very long test"]
async fn c009_t2_PING_PING_REPLY_wait_for_a_ping_req() {
```

**Comment by asmie** [comment]
That was good example - test ignored because it's very long (but it's still production test) would be unable to be simply attached to the tests without pulling all internal tests into the test pool.

**Review by asmie — APPROVED** [review]

**Comment by Rqnsom** [comment]
but it would be good to categorize conformance tests under the `conformance` feature and do the same for the resistance suite
As long as we can ensure those two features are executed by default when we run the most default `cargo test` command

**Pull request merged**
